# adult data
dic_adult_income = {'>50K': 1, '<=50K': 0}
dic_adult_gender = {'Male': 1, 'Female': 0}
dic_adult_race = {'Asian-Pac-Islander': 0,
                 'Other': 0,
                 'White': 1,
                 'Black': 0,
                 'Amer-Indian-Eskimo': 0}

dic_adult_workclass = {'?': 0,
                     'Federal-gov': 1,
                     'State-gov': 2,
                     'Self-emp-not-inc': 3,
                     'Private': 4,
                     'Local-gov': 5,
                     'Without-pay': 6,
                     'Never-worked': 7,
                     'Self-emp-inc': 8}

dic_adult_education = {'HS-grad': 0,
                     'Assoc-acdm': 1,
                     'Some-college': 2,
                     '11th': 3,
                     '1st-4th': 4,
                     'Preschool': 5,
                     'Bachelors': 6,
                     '9th': 7,
                     '5th-6th': 8,
                     '7th-8th': 9,
                     'Prof-school': 10,
                     'Assoc-voc': 11,
                     'Masters': 12,
                     '12th': 13,
                     'Doctorate': 14,
                     '10th': 15}

dic_adult_marital_status = {'Married-AF-spouse': 0,
                     'Widowed': 1,
                     'Never-married': 2,
                     'Married-spouse-absent': 3,
                     'Separated': 4,
                     'Divorced': 5,
                     'Married-civ-spouse': 6}

dic_adult_occupation = {'Priv-house-serv': 0,
                     '?': 1,
                     'Exec-managerial': 2,
                     'Other-service': 3,
                     'Protective-serv': 4,
                     'Handlers-cleaners': 5,
                     'Farming-fishing': 6,
                     'Adm-clerical': 7,
                     'Transport-moving': 8,
                     'Craft-repair': 9,
                     'Tech-support': 10,
                     'Sales': 11,
                     'Machine-op-inspct': 12,
                     'Prof-specialty': 13,
                     'Armed-Forces': 14}

dic_adult_relationship = {'Husband': 0,
                     'Not-in-family': 1,
                     'Wife': 2,
                     'Other-relative': 3,
                     'Own-child': 4,
                     'Unmarried': 5}

dic_adult_native_country = {'Hong': 0,
                         'Mexico': 1,
                         'Greece': 2,
                         'Portugal': 3,
                         'Poland': 4,
                         'China': 5,
                         'Thailand': 6,
                         'Trinadad&Tobago': 7,
                         'Laos': 8,
                         'Haiti': 9,
                         '?': 10,
                         'Hungary': 11,
                         'South': 12,
                         'Scotland': 13,
                         'Holand-Netherlands': 14,
                         'Japan': 15,
                         'Italy': 16,
                         'Puerto-Rico': 17,
                         'Guatemala': 18,
                         'Canada': 19,
                         'Vietnam': 20,
                         'Cuba': 21,
                         'England': 22,
                         'Philippines': 23,
                         'United-States': 24,
                         'Yugoslavia': 25,
                         'Honduras': 26,
                         'Nicaragua': 27,
                         'India': 28,
                         'Germany': 29,
                         'Outlying-US(Guam-USVI-etc)': 30,
                         'Peru': 31,
                         'Ecuador': 32,
                         'Ireland': 33,
                         'France': 34,
                         'Dominican-Republic': 35,
                         'Cambodia': 36,
                         'El-Salvador': 37,
                         'Columbia': 38,
                         'Iran': 39,
                         'Jamaica': 40,
                         'Taiwan': 41}



